const en = {
  appTitle: "Abandoned but not Forgotten",
  appKicker: "NASA Space Apps Challenge",
  landingLead: "Machines we left on other worlds.",
  landingBody:
    "Some were left on purpose. Some went silent. A few are still working. All of them are still on the Moon or Mars. Turn the globe and read where they are.",
  enterMoon: "Enter the Moon",
  enterMars: "Enter Mars",
  dragHint: "Drag to turn the world. Scroll to come closer.",
  explore: "Explore",
  moon: "Moon",
  mars: "Mars",
  searchLabel: "Search objects, missions, and places",
  searchPlaceholder: "Search Eagle, Jezero, Viking…",
  about: "About",
  help: "Help",
  language: "Language",
  objects: "Objects",
  filters: "Filters",
  timeline: "Timeline",
  sources: "Sources",
  close: "Close",
  resetView: "Reset view",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  autoRotate: "Auto-rotate",
  fullscreen: "Fullscreen",
  whatIsIt: "What it is",
  whatHappened: "What happened",
  whyLeft: "Why it remains",
  whyItMatters: "Why it matters",
  location: "Location",
  mission: "Mission",
  status: "Status",
  type: "Type",
  precision: "Precision",
  coordinates: "Coordinates",
  agency: "Agency",
  arrived: "Arrived",
  launch: "Launch",
  ended: "Ended",
  noResults: "Nothing matches that search.",
  noObjects: "No objects match these filters.",
  loadingSurface: "Unfolding the surface",
  sceneError: "The globe could not start. The object list still works.",
  dataError: "The local catalog failed validation.",
  clearFilters: "Clear filters",
  throughYear: "Show arrivals through",
  allMissions: "All missions",
  objectCount: "showing",
  clusterChoose: "Several objects share this view. Choose one.",
  backHome: "Home",
  howToTitle: "How to look",
  howToBody:
    "Drag to rotate a full turn. Scroll or pinch to zoom. Click a light to open its story. Search, the list, and the timeline reach the same objects without using the globe.",
  reducedMotion: "Reduced motion is on. The globe will not spin by itself, and the camera will jump instead of glide.",
  textureCredit: "Globe textures",
  coordinateNote:
    "Markers use one shared latitude/longitude conversion. Longitudes are east-positive, from −180° to 180°. A published west longitude is stored with the opposite sign.",
  photograph: "Photograph",
  atAGlance: "At a glance",
  stillOperating: "Still operating. No end date is recorded.",
  recordedSpan: "days between the recorded arrival and the recorded end",
  skyCredit: "Night sky",
  skyNote:
    "The background is a celestial sphere. Stars are those brighter than visual magnitude 5.5 in the HYG compilation of the Hipparcos catalog. The pale band follows the galactic equator. This is not the sky as seen from a landing site on a particular day.",
  offlineNote: "The catalog, interface, globe maps, and object photographs are stored with the app. Source links still need a network.",
  notLive: "Active rovers are marked at their documented landing sites. This app does not follow them live.",
  openList: "Object list",
  helpTitle: "Looking around",
  clearSelection: "Close story",
  objectives: "Objectives",
  region: "Region",
  externalLink: "Opens in a new tab",
  unknownDate: "Not recorded",
  legend: "Marker colors",
  onThisWorld: "On this world",
  statusLabels: {
    active: "Active",
    inactive: "Inactive",
    mission_complete: "Mission complete",
    communication_lost: "Contact lost",
    destroyed: "Destroyed",
    impacted: "Impacted",
    unknown: "Status not asserted",
  },
  typeLabels: {
    lander: "Lander",
    rover: "Rover",
    instrument: "Instrument",
    descent_stage: "Descent stage",
    spacecraft_component: "Component",
    impact_hardware: "Impact hardware",
    experiment: "Experiment",
    other: "Other",
  },
  precisionLabels: {
    exact: "Surveyed",
    approximate: "Approximate",
    estimated: "Estimated",
    unknown: "Unknown",
  },
};

const bn: typeof en = {
  appTitle: "পরিত্যক্ত, কিন্তু বিস্মৃত নয়",
  appKicker: "নাসা স্পেস অ্যাপস চ্যালেঞ্জ",
  landingLead: "অন্য জগতে আমরা যা রেখে এসেছি।",
  landingBody:
    "কিছু ইচ্ছে করে রাখা। কিছু নীরব হয়ে গেছে। কয়েকটি এখনও কাজ করছে। সবকটি এখনও চাঁদে বা মঙ্গলে আছে। গোলকটি ঘুরিয়ে পড়ুন সেগুলো কোথায়।",
  enterMoon: "চাঁদে ঢুকুন",
  enterMars: "মঙ্গলে ঢুকুন",
  dragHint: "জগৎ ঘোরাতে টানুন। কাছে আসতে স্ক্রল করুন।",
  explore: "অন্বেষণ",
  moon: "চাঁদ",
  mars: "মঙ্গল",
  searchLabel: "বস্তু, অভিযান ও স্থান খুঁজুন",
  searchPlaceholder: "ঈগল, জেজেরো, ভাইকিং খুঁজুন…",
  about: "পরিচিতি",
  help: "সহায়তা",
  language: "ভাষা",
  objects: "বস্তু",
  filters: "ছাঁকনি",
  timeline: "সময়রেখা",
  sources: "উৎস",
  close: "বন্ধ",
  resetView: "দৃশ্য রিসেট",
  zoomIn: "বড় করুন",
  zoomOut: "ছোট করুন",
  autoRotate: "স্বয়ংক্রিয় ঘূর্ণন",
  fullscreen: "পূর্ণ পর্দা",
  whatIsIt: "এটি কী",
  whatHappened: "কী হয়েছিল",
  whyLeft: "কেন রয়ে গেছে",
  whyItMatters: "কেন এটি গুরুত্বপূর্ণ",
  location: "অবস্থান",
  mission: "অভিযান",
  status: "অবস্থা",
  type: "ধরন",
  precision: "নির্ভুলতা",
  coordinates: "স্থানাঙ্ক",
  agency: "সংস্থা",
  arrived: "পৌঁছেছে",
  launch: "উৎক্ষেপণ",
  ended: "সমাপ্তি",
  noResults: "এই খোঁজে কিছু মেলেনি।",
  noObjects: "এই ছাঁকনিতে কোনো বস্তু নেই।",
  loadingSurface: "পৃষ্ঠ খুলছে",
  sceneError: "গোলক চালু হয়নি। বস্তুর তালিকা এখনও কাজ করে।",
  dataError: "স্থানীয় তালিকা যাচাইয়ে ব্যর্থ।",
  clearFilters: "ছাঁকনি মুছুন",
  throughYear: "এই বছর পর্যন্ত অবতরণ",
  allMissions: "সব অভিযান",
  objectCount: "দেখাচ্ছে",
  clusterChoose: "এই দৃশ্যে একাধিক বস্তু। একটি বেছে নিন।",
  backHome: "প্রথম পাতা",
  howToTitle: "কীভাবে দেখবেন",
  howToBody:
    "পুরো এক পাক ঘোরাতে টানুন। জুম করতে স্ক্রল বা চিমটি দিন। একটি আলোতে ক্লিক করলে তার গল্প খোলে। খোঁজ, তালিকা ও সময়রেখা গোলক ছাড়াই একই বস্তুতে পৌঁছায়।",
  reducedMotion: "কম গতি চালু আছে। গোলক নিজে ঘুরবে না, এবং ক্যামেরা গড়িয়ে না গিয়ে লাফিয়ে যাবে।",
  textureCredit: "গোলকের মানচিত্র",
  coordinateNote:
    "চিহ্নগুলো একই অক্ষাংশ/দ্রাঘিমা রূপান্তর ব্যবহার করে। দ্রাঘিমা পূর্ব-ধনাত্মক, −১৮০° থেকে ১৮০°। প্রকাশিত পশ্চিম দ্রাঘিমা উল্টো চিহ্নে রাখা।",
  photograph: "আলোকচিত্র",
  atAGlance: "এক নজরে",
  stillOperating: "এখনও চলছে। সমাপ্তির তারিখ লিপিবদ্ধ নয়।",
  recordedSpan: "দিন, নথিভুক্ত পৌঁছানো ও সমাপ্তির মধ্যে",
  skyCredit: "রাতের আকাশ",
  skyNote:
    "পেছনের আকাশ একটি খ-গোলক। হিপ্পারকোস তালিকার এইচওয়াইজি সংকলনে দৃশ্যমান ৫.৫ মাত্রার চেয়ে উজ্জ্বল তারাগুলো আছে। ফিকে বলয়টি ছায়াপথের বিষুবরেখা। এটি কোনো অবতরণস্থল থেকে কোনো নির্দিষ্ট দিনের আকাশ নয়।",
  offlineNote: "তালিকা, ইন্টারফেস, গোলকের মানচিত্র ও বস্তুর আলোকচিত্র অ্যাপের সঙ্গে আছে। উৎসের লিঙ্কে নেটওয়ার্ক লাগে।",
  notLive: "সক্রিয় রোভার তাদের নথিভুক্ত অবতরণস্থলে চিহ্নিত। এই অ্যাপ তাদের তাৎক্ষণিক অনুসরণ করে না।",
  openList: "বস্তুর তালিকা",
  helpTitle: "চারপাশ দেখা",
  clearSelection: "গল্প বন্ধ",
  objectives: "উদ্দেশ্য",
  region: "অঞ্চল",
  externalLink: "নতুন ট্যাবে খুলবে",
  unknownDate: "লিপিবদ্ধ নয়",
  legend: "চিহ্নের রং",
  onThisWorld: "এই জগতে",
  statusLabels: {
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    mission_complete: "অভিযান সম্পন্ন",
    communication_lost: "যোগাযোগ বিচ্ছিন্ন",
    destroyed: "ধ্বংস",
    impacted: "সংঘাত",
    unknown: "অবস্থা বলা হয়নি",
  },
  typeLabels: {
    lander: "ল্যান্ডার",
    rover: "রোভার",
    instrument: "যন্ত্র",
    descent_stage: "অবতরণ স্তর",
    spacecraft_component: "যন্ত্রাংশ",
    impact_hardware: "সংঘাতের হার্ডওয়্যার",
    experiment: "পরীক্ষা",
    other: "অন্যান্য",
  },
  precisionLabels: {
    exact: "জরিপকৃত",
    approximate: "আনুমানিক",
    estimated: "অনুমিত",
    unknown: "অজানা",
  },
};

export const copy = { en, bn };
export type Copy = typeof en;
export type Lang = keyof typeof copy;
